import type { Snippet } from './react-snippets';

export const shadcnSnippets: Snippet[] = [
  {
    label: 'Button',
    insertText: [
      'import { Button } from "@/components/ui/button";',
      '',
      '<Button variant="${1|default,destructive,outline,secondary,ghost,link|}" size="${2|default,sm,lg,icon|}">',
      '\t${3:Click me}',
      '</Button>',
    ].join('\n'),
    detail: 'shadcn/ui Button component',
  },
  {
    label: 'Card',
    insertText: [
      'import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";',
      '',
      '<Card>',
      '\t<CardHeader>',
      '\t\t<CardTitle>${1:Title}</CardTitle>',
      '\t\t<CardDescription>${2:Description}</CardDescription>',
      '\t</CardHeader>',
      '\t<CardContent>',
      '\t\t${3:Content}',
      '\t</CardContent>',
      '</Card>',
    ].join('\n'),
    detail: 'shadcn/ui Card component',
  },
  {
    label: 'Dialog',
    insertText: [
      'import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";',
      '',
      '<Dialog>',
      '\t<DialogTrigger asChild>',
      '\t\t<Button variant="outline">${1:Open}</Button>',
      '\t</DialogTrigger>',
      '\t<DialogContent>',
      '\t\t<DialogHeader>',
      '\t\t\t<DialogTitle>${2:Title}</DialogTitle>',
      '\t\t\t<DialogDescription>${3:Description}</DialogDescription>',
      '\t\t</DialogHeader>',
      '\t\t${4:Content}',
      '\t</DialogContent>',
      '</Dialog>',
    ].join('\n'),
    detail: 'shadcn/ui Dialog component',
  },
  {
    label: 'Tabs',
    insertText: [
      'import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";',
      '',
      '<Tabs defaultValue="${1:tab1}">',
      '\t<TabsList>',
      '\t\t<TabsTrigger value="${1:tab1}">${2:Tab 1}</TabsTrigger>',
      '\t\t<TabsTrigger value="${3:tab2}">${4:Tab 2}</TabsTrigger>',
      '\t</TabsList>',
      '\t<TabsContent value="${1:tab1}">${5:Content 1}</TabsContent>',
      '\t<TabsContent value="${3:tab2}">${6:Content 2}</TabsContent>',
      '</Tabs>',
    ].join('\n'),
    detail: 'shadcn/ui Tabs component',
  },
  {
    label: 'Select',
    insertText: [
      'import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";',
      '',
      '<Select>',
      '\t<SelectTrigger>',
      '\t\t<SelectValue placeholder="${1:Select...}" />',
      '\t</SelectTrigger>',
      '\t<SelectContent>',
      '\t\t<SelectItem value="${2:value1}">${3:Label 1}</SelectItem>',
      '\t\t<SelectItem value="${4:value2}">${5:Label 2}</SelectItem>',
      '\t</SelectContent>',
      '</Select>',
    ].join('\n'),
    detail: 'shadcn/ui Select component',
  },
  {
    label: 'DropdownMenu',
    insertText: [
      'import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";',
      '',
      '<DropdownMenu>',
      '\t<DropdownMenuTrigger asChild>',
      '\t\t<Button variant="outline">${1:Options}</Button>',
      '\t</DropdownMenuTrigger>',
      '\t<DropdownMenuContent>',
      '\t\t<DropdownMenuItem>${2:Item 1}</DropdownMenuItem>',
      '\t\t<DropdownMenuItem>${3:Item 2}</DropdownMenuItem>',
      '\t</DropdownMenuContent>',
      '</DropdownMenu>',
    ].join('\n'),
    detail: 'shadcn/ui DropdownMenu component',
  },
  {
    label: 'Input',
    insertText: [
      'import { Input } from "@/components/ui/input";',
      'import { Label } from "@/components/ui/label";',
      '',
      '<div className="space-y-2">',
      '\t<Label htmlFor="${1:field}">${2:Label}</Label>',
      '\t<Input id="${1:field}" placeholder="${3:Placeholder}" />',
      '</div>',
    ].join('\n'),
    detail: 'shadcn/ui Input with Label',
  },
];
