import type { SizaTheme } from '@/stores/theme-store';

const FORGE_IDENTITY = {
  name: 'Forge Space',
  primaryHex: '#8B5CF6',
  secondaryHex: '#A78BFA',
  accentHex: '#6D28D9',
  headingFont: 'Plus Jakarta Sans',
  bodyFont: 'DM Sans',
  semantic: {
    success: '#22c55e',
    warning: '#eab308',
    error: '#ef4444',
    info: '#3b82f6',
  },
  neutrals: [
    '#fafafa',
    '#f4f4f5',
    '#e4e4e7',
    '#d4d4d8',
    '#a1a1aa',
    '#71717a',
    '#52525b',
    '#3f3f46',
    '#27272a',
    '#18181b',
  ],
};

export const BUILT_IN_THEMES: SizaTheme[] = [
  {
    id: 'siza-default',
    name: 'Siza Default',
    builtIn: true,
    colorMode: 'dark',
    primaryColor: '#8B5CF6',
    secondaryColor: '#A78BFA',
    accentColor: '#22C55E',
    animation: 'subtle',
    spacing: 'default',
    borderRadius: 'medium',
    typography: 'system',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'clean-light',
    name: 'Clean Light',
    builtIn: true,
    colorMode: 'light',
    primaryColor: '#3B82F6',
    secondaryColor: '#6B7280',
    accentColor: '#10B981',
    animation: 'subtle',
    spacing: 'default',
    borderRadius: 'medium',
    typography: 'sans',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'bold-contrast',
    name: 'Bold Contrast',
    builtIn: true,
    colorMode: 'dark',
    primaryColor: '#EF4444',
    secondaryColor: '#FFFFFF',
    accentColor: '#F59E0B',
    animation: 'standard',
    spacing: 'spacious',
    borderRadius: 'small',
    typography: 'sans',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'nature',
    name: 'Nature',
    builtIn: true,
    colorMode: 'light',
    primaryColor: '#22C55E',
    secondaryColor: '#92400E',
    accentColor: '#F59E0B',
    animation: 'subtle',
    spacing: 'spacious',
    borderRadius: 'large',
    typography: 'serif',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    builtIn: true,
    colorMode: 'dark',
    primaryColor: '#FFFFFF',
    secondaryColor: '#9CA3AF',
    accentColor: '#D1D5DB',
    animation: 'none',
    spacing: 'default',
    borderRadius: 'none',
    typography: 'mono',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'forge-space',
    name: FORGE_IDENTITY.name,
    builtIn: true,
    colorMode: 'dark',
    primaryColor: FORGE_IDENTITY.primaryHex,
    secondaryColor: FORGE_IDENTITY.secondaryHex,
    accentColor: FORGE_IDENTITY.accentHex,
    animation: 'standard',
    spacing: 'default',
    borderRadius: 'medium',
    typography: 'sans',
    brandMeta: {
      brandName: FORGE_IDENTITY.name,
      headingFont: FORGE_IDENTITY.headingFont,
      bodyFont: FORGE_IDENTITY.bodyFont,
      semanticColors: FORGE_IDENTITY.semantic,
      neutrals: FORGE_IDENTITY.neutrals,
    },
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];
