import type { SizaTheme } from '@/stores/theme-store';
import { identity } from '@forgespace/brand-guide';

const sizaFonts = (identity as Record<string, any>).subBrands?.siza;
const neutralHexes = identity.colors.neutral.map((n) => n.hex);

export const BUILT_IN_THEMES: SizaTheme[] = [
  {
    id: 'siza-default',
    name: 'Siza Default',
    builtIn: true,
    colorMode: 'dark',
    primaryColor: '#7C3AED',
    secondaryColor: '#6366F1',
    accentColor: '#22C55E',
    animation: 'subtle',
    spacing: 'default',
    borderRadius: 'medium',
    typography: 'system',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'clean-light',
    name: 'Clean Light',
    builtIn: true,
    colorMode: 'light',
    primaryColor: '#3B82F6',
    secondaryColor: '#6B7280',
    accentColor: '#10B981',
    animation: 'subtle',
    spacing: 'default',
    borderRadius: 'medium',
    typography: 'sans',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'bold-contrast',
    name: 'Bold Contrast',
    builtIn: true,
    colorMode: 'dark',
    primaryColor: '#EF4444',
    secondaryColor: '#FFFFFF',
    accentColor: '#F59E0B',
    animation: 'standard',
    spacing: 'spacious',
    borderRadius: 'small',
    typography: 'sans',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'nature',
    name: 'Nature',
    builtIn: true,
    colorMode: 'light',
    primaryColor: '#22C55E',
    secondaryColor: '#92400E',
    accentColor: '#F59E0B',
    animation: 'subtle',
    spacing: 'spacious',
    borderRadius: 'large',
    typography: 'serif',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    builtIn: true,
    colorMode: 'dark',
    primaryColor: '#FFFFFF',
    secondaryColor: '#9CA3AF',
    accentColor: '#D1D5DB',
    animation: 'none',
    spacing: 'default',
    borderRadius: 'none',
    typography: 'mono',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'forge-space',
    name: identity.name || 'Forge Space',
    builtIn: true,
    colorMode: 'dark',
    primaryColor: identity.colors.primary.hex,
    secondaryColor: identity.colors.secondary.hex,
    accentColor: identity.colors.accent.hex,
    animation: 'standard',
    spacing: 'default',
    borderRadius: 'medium',
    typography: 'sans',
    brandMeta: {
      brandName: identity.name || 'Forge Space',
      headingFont: sizaFonts?.headingFont || 'Plus Jakarta Sans',
      bodyFont: sizaFonts?.bodyFont || 'DM Sans',
      semanticColors: {
        success: identity.colors.semantic.success.hex,
        warning: identity.colors.semantic.warning.hex,
        error: identity.colors.semantic.error.hex,
        info: identity.colors.semantic.info.hex,
      },
      neutrals: neutralHexes.slice(0, 10),
    },
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];
