import { Page, Route } from '@playwright/test';

const MOCK_GENERATION_CODE = [
  "import React from 'react';",
  '',
  'export function MockComponent() {',
  '  return (',
  '    <div className="p-4 rounded-lg bg-surface-1 border border-surface-3">',
  '      <h2 className="text-lg font-semibold">Mock Component</h2>',
  '      <p className="text-text-secondary mt-2">Generated by E2E test mock</p>',
  '    </div>',
  '  );',
  '}',
].join('\n');

export async function mockGenerateAPI(page: Page): Promise<void> {
  await page.route('**/api/generate', async (route: Route) => {
    const chunks = [
      'data: ' + JSON.stringify({ type: 'start', timestamp: Date.now() }) + '\n\n',
      'data: ' +
        JSON.stringify({
          type: 'chunk',
          content: MOCK_GENERATION_CODE,
          timestamp: Date.now(),
        }) +
        '\n\n',
      'data: ' +
        JSON.stringify({
          type: 'quality',
          report: { score: 0.85, passed: true, gates: [] },
          timestamp: Date.now(),
        }) +
        '\n\n',
      'data: ' +
        JSON.stringify({
          type: 'complete',
          code: MOCK_GENERATION_CODE,
          generationId: 'mock-gen-id',
          totalLength: MOCK_GENERATION_CODE.length,
          qualityPassed: true,
          ragEnriched: false,
          provider: 'google',
          timestamp: Date.now(),
        }) +
        '\n\n',
    ];

    await route.fulfill({
      status: 200,
      headers: {
        'Content-Type': 'text/event-stream',
        'Cache-Control': 'no-cache',
      },
      body: chunks.join(''),
    });
  });
}

export async function mockGenerateAPIError(page: Page, statusCode = 500): Promise<void> {
  await page.route('**/api/generate', async (route: Route) => {
    await route.fulfill({
      status: statusCode,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        error: statusCode === 429 ? 'Rate limit exceeded' : 'Internal server error',
      }),
    });
  });
}

export async function mockAuthAPI(page: Page): Promise<void> {
  await page.route('**/auth/v1/token**', async (route: Route) => {
    await route.fulfill({
      status: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        access_token: 'mock-token',
        token_type: 'bearer',
        expires_in: 3600,
        refresh_token: 'mock-refresh',
        user: { id: 'mock-user-id', email: 'test@example.com' },
      }),
    });
  });
}
