insert into public.skills (name, slug, description, category, instructions, source_url, source_type, parameter_schema, preferred_provider, complexity_boost, requires_vision, icon, frameworks) values
(
  'Component Generation',
  'siza-component-generation',
  'Generate production-ready UI components with quality gates, accessibility, and responsive design',
  'component',
  E'Generate production-ready, accessible UI components.\n\n## Requirements\n- Semantic HTML elements (button, nav, dialog, etc.)\n- ARIA attributes for interactive elements\n- Keyboard navigation support (Tab, Enter, Escape)\n- Responsive design using relative units\n- TypeScript interfaces for all props\n- Error and loading states\n- CSS custom properties for theming\n\n## Structure\n1. Props interface with JSDoc descriptions\n2. Component with forwardRef when applicable\n3. Compound component pattern for complex UIs\n4. Event handlers with proper typing\n5. Default prop values\n\n## Quality Gates\n- No inline styles — use utility classes or CSS modules\n- No div soup — use semantic elements\n- All interactive elements must be focusable\n- Color contrast ratio >= 4.5:1\n- Touch targets >= 44x44px on mobile',
  'https://github.com/Forge-Space/siza',
  'official',
  '{"type":"object","properties":{"variant":{"type":"string","enum":["default","outline","ghost","link"],"description":"Component variant style"},"size":{"type":"string","enum":["sm","md","lg"],"description":"Component size"}}}'::jsonb,
  null,
  0.0,
  false,
  'Component',
  '{react,vue,angular,svelte}'
),
(
  'Form Builder',
  'siza-form-builder',
  'Complex forms with validation, multi-step support, 8 presets, and accessible error handling',
  'form',
  E'Build complex, validated forms with great UX.\n\n## Presets\nlogin, signup, contact, checkout, settings, search, feedback, newsletter\n\n## Requirements\n- Schema-based validation (Zod preferred, Yup supported)\n- Accessible error messages linked via aria-describedby\n- Multi-step forms with progress indicator\n- Inline validation on blur, form-level on submit\n- Loading states on submit button\n- Prevent double submission\n\n## Validation Patterns\n- Email: RFC 5322 compliant regex\n- Password: min 8 chars, mixed case, number, special char\n- Phone: E.164 international format\n- Required fields: visual indicator + aria-required\n\n## Error Display\n- Inline errors below each field\n- Error summary at form top for screen readers\n- Focus first error field on submit failure\n- Clear errors on field change\n\n## Multi-Step Architecture\n- Step state managed in parent component\n- Each step validates independently\n- Back navigation preserves entered data\n- Progress bar shows completion percentage',
  'https://github.com/Forge-Space/siza',
  'official',
  '{"type":"object","properties":{"preset":{"type":"string","enum":["login","signup","contact","checkout","settings","search","feedback","newsletter"],"description":"Form preset type"},"validationLib":{"type":"string","enum":["zod","yup","native"],"description":"Validation library"},"multiStep":{"type":"boolean","description":"Enable multi-step form"}}}'::jsonb,
  null,
  0.10,
  false,
  'FormInput',
  '{react,vue,angular,svelte}'
),
(
  'Dashboard Scaffolding',
  'siza-dashboard-scaffolding',
  'Admin dashboards with sidebar navigation, data tables, charts, and responsive layouts',
  'dashboard',
  E'Scaffold admin dashboards with responsive layouts.\n\n## Layout Patterns\n- Collapsible sidebar (240px expanded, 64px collapsed)\n- Top header with breadcrumbs, search, user menu\n- Main content area with scroll\n- Mobile: bottom nav or hamburger drawer\n\n## Data Tables\n- Column sorting (asc/desc/none cycle)\n- Text search with debounce (300ms)\n- Pagination (10/25/50/100 per page)\n- Row selection with bulk actions\n- Responsive: horizontal scroll or stacked cards on mobile\n\n## Metric Cards\n- Value, label, trend indicator (up/down/neutral)\n- Sparkline or mini chart\n- Loading skeleton\n- Grid: 4 columns desktop, 2 tablet, 1 mobile\n\n## Charts\n- Use recharts (React) or chart.js (framework-agnostic)\n- Responsive container with aspect ratio\n- Accessible: provide data table alternative\n- Color palette: 6 distinct, colorblind-safe colors\n\n## Page Structure\n1. Header with page title and primary action\n2. Filter bar (collapsible on mobile)\n3. Metric cards row\n4. Main content (table or chart grid)\n5. Pagination footer',
  'https://github.com/Forge-Space/siza',
  'official',
  '{"type":"object","properties":{"layout":{"type":"string","enum":["sidebar","topnav","minimal"],"description":"Dashboard layout style"},"charts":{"type":"boolean","description":"Include chart components"},"dataTable":{"type":"boolean","description":"Include data table component"}}}'::jsonb,
  null,
  0.20,
  false,
  'LayoutDashboard',
  '{react,vue,angular,svelte}'
),
(
  'Design-to-Code',
  'siza-design-to-code',
  'Convert screenshots and wireframes to component code with color extraction and layout analysis',
  'design',
  E'Convert visual designs to production code.\n\n## Analysis Steps\n1. Identify component boundaries and hierarchy\n2. Extract color palette (primary, secondary, accent, neutrals)\n3. Detect layout pattern (grid columns, flex direction, gaps)\n4. Measure spacing ratios (padding, margins, gaps)\n5. Identify typography (headings, body, captions)\n6. Map interactive elements (buttons, links, inputs)\n\n## Color Extraction\n- Extract dominant colors and map to CSS custom properties\n- Detect background/foreground contrast pairs\n- Generate semantic color tokens (--color-primary, --color-surface)\n\n## Layout Detection\n- Grid: count columns, identify gutter width\n- Flex: determine direction, alignment, wrapping\n- Absolute: identify overlapping elements, z-index layers\n- Responsive: infer breakpoint behavior from element sizes\n\n## Typography\n- Classify text into heading levels (h1-h6)\n- Estimate font size scale ratio\n- Detect font weight variations\n- Map to system font stack or identify custom fonts\n\n## Handling Ambiguity\n- Prefer semantic HTML over visual approximation\n- When spacing is unclear, use 4px/8px grid system\n- Default to flex layout unless clear grid pattern\n- Ask for clarification on interactive behavior',
  'https://github.com/Forge-Space/siza',
  'official',
  '{"type":"object","properties":{"fidelity":{"type":"string","enum":["exact","approximate","wireframe"],"description":"How closely to match the design"},"extractColors":{"type":"boolean","description":"Extract and apply color palette"}}}'::jsonb,
  'anthropic',
  0.15,
  true,
  'Paintbrush',
  '{react,vue,angular,svelte}'
),
(
  'Accessibility Audit',
  'siza-accessibility-audit',
  'WCAG 2.1 AA compliance checks with ARIA patterns, keyboard navigation, and screen reader support',
  'accessibility',
  E'Ensure WCAG 2.1 AA compliance in generated code.\n\n## Checklist\n\n### Perceivable\n- All images have descriptive alt text\n- Color is not the only means of conveying information\n- Text contrast ratio >= 4.5:1 (normal), >= 3:1 (large)\n- Content is readable at 200% zoom\n- Captions for audio/video content\n\n### Operable\n- All functionality available via keyboard\n- No keyboard traps (Escape always exits)\n- Focus order matches visual order\n- Focus indicators visible (outline or ring)\n- Touch targets >= 44x44px\n- No content that flashes more than 3 times/second\n\n### Understandable\n- Form inputs have visible labels\n- Error messages are descriptive and actionable\n- Consistent navigation patterns\n- Language attribute on html element\n\n### Robust\n- Valid semantic HTML\n- ARIA roles used correctly (not redundant with semantics)\n- Name, role, value exposed to assistive technology\n- Status messages use aria-live regions\n\n## Common ARIA Patterns\n- Dialog: role=dialog, aria-modal, aria-labelledby, focus trap\n- Tabs: role=tablist/tab/tabpanel, aria-selected, arrow key nav\n- Menu: role=menu/menuitem, aria-expanded, Escape to close\n- Combobox: role=combobox, aria-expanded, aria-activedescendant\n- Alert: role=alert or aria-live=assertive for errors\n\n## Anti-Patterns to Avoid\n- div with onClick instead of button\n- Placeholder as label\n- aria-label on non-interactive elements\n- tabindex > 0\n- Removing focus outline without replacement\n- Using title attribute for essential information',
  'https://github.com/Forge-Space/siza',
  'official',
  '{"type":"object","properties":{"level":{"type":"string","enum":["A","AA","AAA"],"description":"WCAG conformance level"},"includeAria":{"type":"boolean","description":"Include detailed ARIA patterns"}}}'::jsonb,
  null,
  0.05,
  false,
  'ShieldCheck',
  '{react,vue,angular,svelte}'
);
